USIF_SIM_THRESHOLD = 0.5
SLIDING_WINDOW_SIM_THRESHOLD = 0.5
SLIDING_WINDOW_SIZE = 2

GLOVE_MODEL_PATH = "models/glove"
GLOVE_FILE = "babylm.10M.50d.txt"

EVAL_PATH = "eval"
AUG_PATH = "aug"
WORDVEC_PATH = "models/mds"

BABYLM_ORIGINAL_DATA_PATH = "data/babylm/original"
BABYLM_FOLDERS = ['10M']

VERBOSITY = 1  # 0: ERROR, 1: INFO, 2: DEBUG